name:
environment: DEV
kubernetesVersion: 1.13.0
kubernetesApiAccess:
  - 0.0.0.0/0
aws:
  vpcId:
  networkAddress:
  region:
dnsZone:
awsDnsZoneId:
sshAccess:
  - 82.25.28.5/32
  - 164.39.87.162/32
clusterStateStorage:
instances:
  master:
    type: t2.medium
    image: kope.io/k8s-1.13-debian-stretch-amd64-hvm-ebs-2019-08-16
    min: 1
    max: 1
  node:
    type: t2.large
    image: kope.io/k8s-1.13-debian-stretch-amd64-hvm-ebs-2019-08-16
    min: 3
    max: 3
  bastion:
    type: t2.micro
    image: kope.io/k8s-1.13-debian-stretch-amd64-hvm-ebs-2019-08-16
    min: 1
    max: 1